const L=window.CHRONICLE_LESSONS;
const KEY='chronicle_state_v1';
const defaults={onboarded:false,goal:8,xp:0,days:[],completed:{},attempts:{},reviews:[],mix:{'Bahamian History':40,'Caribbean History':25,'World History':20,'American History':15},settings:{reduced:false,text:100,sound:false},tab:'today'};
let S=load();
function load(){try{return {...structuredClone(defaults),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function day(){return new Date().toISOString().slice(0,10)}
function touchDay(){if(!S.days.includes(day())) S.days.push(day());}
function esc(x){return String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function app(html){document.getElementById('app').innerHTML=html}
function notify(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.append(d);setTimeout(()=>d.remove(),1600)}
function pct(path){const a=L.filter(x=>x.path===path),d=a.filter(x=>S.completed[x.id]).length;return Math.round(d/a.length*100)}
function due(){const n=Date.now();return S.reviews.filter(r=>!r.done && new Date(r.due).getTime()<=n)}
function chooseDaily(){const incomplete=L.filter(x=>!S.completed[x.id]);if(!incomplete.length)return L[new Date().getDate()%L.length];const paths=Object.entries(S.mix).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);for(const p of paths){const q=incomplete.find(x=>x.path===p);if(q)return q}return incomplete[0]}
function nav(active){const items=[['today','⌂','Today'],['paths','◉','Paths'],['review','↻','Review'],['timeline','⌛','Timeline'],['profile','◎','Profile']];return `<nav class="bottomnav">${items.map(([id,ic,n])=>`<button class="${active===id?'active':''}" onclick="go('${id}')"><span class="navicon">${ic}</span>${n}</button>`).join('')}</nav>`}
function shell(body,active){app(`<main class="app"><header class="topbar"><div class="brand">Chronicle<small>History you remember</small></div><div class="pill">${S.xp} XP</div></header><section class="page">${body}</section>${nav(active)}</main>`)}
function go(tab){S.tab=tab;save();({today,paths,review,timeline,profile}[tab]||today)()}
function onboarding(){app(`<main class="app"><section class="page" style="padding-top:32px"><div class="hero"><div class="eyebrow">Your private history course</div><h1>Learn history like a story. Remember it like a place.</h1><p>Short cinematic lessons, retrieval practice, and spaced review. No ads. No subscription. Progress stays on this device.</p><button class="cta gold" onclick="onboardStep2()">Begin the journey</button></div><h2 class="section-title">Built for recall, not scrolling</h2><div class="grid two"><div class="stat"><b>5–10</b><span>minutes per day</span></div><div class="stat"><b>4</b><span>history paths</span></div><div class="stat"><b>16</b><span>starter lessons</span></div><div class="stat"><b>1–90</b><span>day review cycle</span></div></div></section></main>`)}
function onboardStep2(){app(`<main class="app"><section class="page" style="padding-top:38px"><div class="card"><div class="eyebrow">Set your rhythm</div><h1 class="section-title" style="margin-top:8px">How long should a normal lesson feel?</h1><div class="quiz-options">${[5,8,10].map(v=>`<button class="quiz-option" onclick="finishOnboard(${v})"><b>${v} minutes</b><br><span class="muted">${v===5?'Fastest daily habit':v===8?'Balanced default':'Deeper story mode'}</span></button>`).join('')}</div><p class="muted">Bahamian History starts as your priority path. You can change the mix later.</p></div></section></main>`)}
function finishOnboard(v){S.onboarded=true;S.goal=v;touchDay();save();today()}
function today(){const l=chooseDaily(),dr=due();shell(`<div class="hero"><div class="eyebrow">Today’s ${S.goal}-minute journey · ${esc(l.path)}</div><h1>${esc(l.title)}</h1><p>${esc(l.hook)}</p><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="cta gold" onclick="startLesson('${l.id}')">${S.completed[l.id]?'Revisit lesson':'Start lesson'}</button><span class="pill">${l.era} · ${l.minutes} min</span></div></div><div class="grid two"><div class="stat"><b>${S.days.length}</b><span>active learning days</span></div><div class="stat"><b>${dr.length}</b><span>reviews due now</span></div></div><h2 class="section-title">One thing to remember</h2><div class="card"><div class="eyebrow">Memory anchor</div><p style="font-size:18px;line-height:1.55">${esc(l.memory)}</p></div><h2 class="section-title">Your four worlds</h2><div class="grid two">${['Bahamian History','Caribbean History','World History','American History'].map(p=>`<div class="card path-card"><div class="eyebrow">${pct(p)}% complete</div><h3>${p}</h3><div class="progress"><i style="width:${pct(p)}%"></i></div></div>`).join('')}</div>`, 'today')}
function paths(){shell(`<div class="eyebrow">Learning paths</div><h1 class="section-title" style="margin-top:8px">History as connected journeys</h1>${['Bahamian History','Caribbean History','World History','American History'].map(p=>`<section><div class="card path-card"><div class="eyebrow">${pct(p)}% complete</div><h3>${p}</h3><p class="muted">${p==='Bahamian History'?'Priority path · islands, empire, freedom and identity':p==='Caribbean History'?'Indigenous worlds, plantation systems, revolution and emancipation':p==='World History'?'Cities, rivers, networks and shocks across civilizations':'Indigenous nations, revolution, civil war and citizenship'}</p><div class="progress"><i style="width:${pct(p)}%"></i></div></div><div class="lesson-list" style="margin-top:10px">${L.filter(x=>x.path===p).map((x,i)=>`<div class="lesson-row ${S.completed[x.id]?'done':''}"><div class="orb">${S.completed[x.id]?'✓':i+1}</div><div><h3>${esc(x.title)}</h3><p>${esc(x.era)} · ${x.minutes} min</p></div><button onclick="startLesson('${x.id}')">${S.completed[x.id]?'Review':'Start'}</button></div>`).join('')}</div></section>`).join('')}`,'paths')}
let player=null;
function startLesson(id){const l=L.find(x=>x.id===id);player={l,step:0,quiz:0,score:0,answered:false,selected:null};renderLesson()}
function cards(l){return [
 {k:'Cold open',h:l.title,p:l.hook},
 {k:'Where & when',h:`${l.region} · ${l.era}`,p:`Place this story on the mental map first. Region: ${l.region}. Period: ${l.era}. Your job is to connect every fact that follows back to this place and time.`},
 ...l.beats.map((b,i)=>({k:`Story beat ${i+1}`,h:['See the system','Watch the change','Follow the people','Lock the pattern'][i%4],p:b})),
 {k:'Memory anchor',h:'Make one picture in your mind',p:l.memory,anchor:true},
 {k:'Why it mattered',h:'The consequence',p:l.mattered},
 {k:'Connect it',h:'Link this to another story',p:l.connect},
 {k:'Retrieval',h:'Now close the loop',p:'Without looking back, say the story aloud in 30 seconds. Use three anchors: WHERE/WHEN → WHAT CHANGED → WHY IT MATTERED.',anchor:true}
]}
function renderLesson(){const {l,step}=player,c=cards(l);if(step>=c.length)return renderQuiz();const x=c[step];app(`<main class="story-shell"><div class="story-progress"><i style="width:${Math.round((step)/(c.length+l.quiz.length)*100)}%"></i></div><div class="story-head"><button class="iconbtn" onclick="go('today')">×</button><span class="pill">${step+1}/${c.length+l.quiz.length}</span></div><article class="story-card"><div class="story-kicker">${x.k}</div><h2>${esc(x.h)}</h2>${x.anchor?`<div class="memory-anchor"><p>${esc(x.p)}</p></div>`:`<p>${esc(x.p)}</p>`}${step===1?`<div><span class="tag">${esc(l.region)}</span><span class="tag">${esc(l.era)}</span><span class="tag">${esc(l.status)}</span></div>`:''}</article><div class="story-actions"><button class="cta ${step?'secondary':''}" onclick="${step?'prevCard()':'go(\'today\')'}">${step?'Back':'Exit'}</button><button class="cta gold" onclick="nextCard()">${step===c.length-1?'Start quiz':'Continue'}</button></div></main>`)}
function nextCard(){player.step++;renderLesson()}function prevCard(){player.step=Math.max(0,player.step-1);renderLesson()}
function renderQuiz(){const {l,quiz}=player;if(quiz>=l.quiz.length)return finishLesson();const q=l.quiz[quiz];app(`<main class="story-shell"><div class="story-progress"><i style="width:${Math.round((cards(l).length+quiz)/(cards(l).length+l.quiz.length)*100)}%"></i></div><div class="story-head"><button class="iconbtn" onclick="go('today')">×</button><span class="pill">Question ${quiz+1}/${l.quiz.length}</span></div><article class="story-card"><div class="story-kicker">Retrieve before rereading</div><h2 style="font-size:34px">${esc(q.q)}</h2><div class="quiz-options">${q.o.map((o,i)=>`<button class="quiz-option ${player.answered?(i===q.a?'correct':(i===player.selected?'wrong':'')):''}" onclick="answerQuiz(${i})" ${player.answered?'disabled':''}>${esc(o)}</button>`).join('')}</div>${player.answered?`<div class="feedback"><b>${player.selected===q.a?'Correct.':'Not quite.'}</b> ${esc(q.e)}</div>`:''}</article><div class="story-actions">${player.answered?`<button class="cta gold" onclick="nextQuiz()">${quiz===l.quiz.length-1?'Finish lesson':'Next question'}</button>`:'<button class="cta secondary" disabled>Choose an answer first</button>'}</div></main>`)}
function answerQuiz(i){if(player.answered)return;player.selected=i;player.answered=true;if(i===player.l.quiz[player.quiz].a)player.score++;renderQuiz()}
function nextQuiz(){player.quiz++;player.answered=false;player.selected=null;renderQuiz()}
function scheduleReviews(l,score){const intervals=[1,3,7,14,30,90],ratio=score/l.quiz.length;intervals.forEach((d,i)=>{const dueDate=new Date();dueDate.setDate(dueDate.getDate()+Math.max(1,ratio<.5&&i===0?1:d));S.reviews.push({id:`${l.id}-${Date.now()}-${i}`,lessonId:l.id,due:dueDate.toISOString(),stage:i,done:false})})}
function finishLesson(){const {l,score}=player;touchDay();const first=!S.completed[l.id];S.completed[l.id]={date:day(),score,total:l.quiz.length};S.attempts[l.id]=(S.attempts[l.id]||0)+1;S.xp+=score*10+(first?20:5);if(first)scheduleReviews(l,score);save();const pctscore=Math.round(score/l.quiz.length*100);app(`<main class="story-shell"><article class="story-card"><div class="story-kicker">Journey complete</div><h2>${pctscore}% recall</h2><p>You recalled ${score} of ${l.quiz.length} questions. The lesson is now in your spaced-review cycle.</p><div class="memory-anchor"><p><b>Keep this:</b> ${esc(l.memory)}</p></div><p class="muted"><b>Source note:</b> ${esc(l.source)}</p></article><div class="story-actions"><button class="cta gold" onclick="go('today')">Back to Today</button><button class="cta secondary" onclick="go('review')">Review queue</button></div></main>`)}
function review(){const d=due();if(!d.length){shell(`<div class="eyebrow">Spaced repetition</div><h1 class="section-title" style="margin-top:8px">Review queue</h1><div class="card empty"><h2>Nothing due right now.</h2><p>Your next review appears automatically when memory needs another retrieval attempt.</p></div><h2 class="section-title">How the rhythm works</h2><div class="card"><p>New material returns after roughly <b>1, 3, 7, 14, 30, and 90 days</b>. Retrieval comes before rereading so your brain has to reconstruct the answer.</p></div>`,'review');return}const r=d[0],l=L.find(x=>x.id===r.lessonId);shell(`<div class="eyebrow">${d.length} due now</div><h1 class="section-title" style="margin-top:8px">Review: ${esc(l.title)}</h1><div class="card"><div class="review-prompt">Without opening the lesson, explain: <b>${esc(l.mattered)}</b></div><p class="muted">Say it aloud in your own words. Then rate how well you recalled it.</p><div class="conf-row"><button class="cta secondary" onclick="rateReview('${r.id}',0)">Blank</button><button class="cta secondary" onclick="rateReview('${r.id}',1)">Hard</button><button class="cta gold" onclick="rateReview('${r.id}',2)">Good</button></div></div><div class="card" style="margin-top:14px"><div class="eyebrow">Memory cue</div><p>${esc(l.memory)}</p></div>`,'review')}
function rateReview(id,rating){const r=S.reviews.find(x=>x.id===id);r.done=true;r.rating=rating;r.doneAt=new Date().toISOString();if(rating<2){const n=new Date();n.setDate(n.getDate()+(rating===0?1:3));S.reviews.push({id:`${r.lessonId}-${Date.now()}-redo`,lessonId:r.lessonId,due:n.toISOString(),stage:r.stage,done:false})}S.xp+=rating===2?10:5;save();notify('Review saved');review()}
function timeline(){const paths=['All','Bahamian History','Caribbean History','World History','American History'];const f=window.timelineFilter||'All',items=L.filter(x=>f==='All'||x.path===f).sort((a,b)=>a.year-b.year);shell(`<div class="eyebrow">See events together</div><h1 class="section-title" style="margin-top:8px">Timeline</h1><div class="card"><label class="muted">Filter region</label><select style="width:100%;margin-top:8px;background:#0d2130;color:var(--ink);border:1px solid var(--line);padding:12px;border-radius:12px" onchange="window.timelineFilter=this.value;timeline()">${paths.map(p=>`<option ${p===f?'selected':''}>${p}</option>`).join('')}</select></div><div class="timeline" style="margin-top:20px">${items.map(x=>`<div class="timeline-item"><div class="eyebrow">${esc(x.era)} · ${esc(x.path)}</div><h3>${esc(x.title)}</h3><p class="muted">${esc(x.mattered)}</p><button class="cta secondary" onclick="startLesson('${x.id}')">Open lesson</button></div>`).join('')}</div><div class="card"><div class="eyebrow">Meanwhile…</div><p>Use this timeline to notice overlap. The point is not just “what happened next?” but “what else was happening elsewhere at the same time?”</p></div>`,'timeline')}
function profile(){shell(`<div class="eyebrow">Your learning system</div><h1 class="section-title" style="margin-top:8px">Profile & settings</h1><div class="card"><div class="setting"><div><b>Daily lesson</b><div class="muted">Target length</div></div><select onchange="S.goal=+this.value;save()">${[5,8,10].map(v=>`<option value="${v}" ${S.goal===v?'selected':''}>${v} min</option>`).join('')}</select></div><div class="setting"><div><b>Text size</b><div class="muted">Reading comfort</div></div><select onchange="S.settings.text=+this.value;document.documentElement.style.fontSize=this.value+'%';save()">${[90,100,110,120].map(v=>`<option value="${v}" ${S.settings.text===v?'selected':''}>${v}%</option>`).join('')}</select></div><div class="setting"><div><b>Reduced motion</b><div class="muted">Accessibility</div></div><input type="checkbox" ${S.settings.reduced?'checked':''} onchange="S.settings.reduced=this.checked;save()"></div></div><h2 class="section-title">Your data</h2><div class="grid"><button class="cta secondary" onclick="exportData()">Export progress JSON</button><label class="cta secondary">Import progress JSON<input type="file" accept="application/json" hidden onchange="importData(this.files[0])"></label><button class="cta secondary" onclick="resetData()">Reset all progress</button></div><div class="card" style="margin-top:18px"><div class="eyebrow">Privacy</div><p>No account, ads, trackers, subscription, or paid API. Your learning progress is stored in this browser unless you export it.</p></div>`,'profile')}
function exportData(){const b=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='chronicle-progress.json';a.click();URL.revokeObjectURL(u)}
function importData(f){if(!f)return;const r=new FileReader();r.onload=()=>{try{S={...structuredClone(defaults),...JSON.parse(r.result)};save();notify('Progress imported');profile()}catch{notify('Invalid progress file')}};r.readAsText(f)}
function resetData(){if(confirm('Reset Chronicle progress on this device?')){S=structuredClone(defaults);save();onboarding()}}
window.go=go;window.onboardStep2=onboardStep2;window.finishOnboard=finishOnboard;window.startLesson=startLesson;window.nextCard=nextCard;window.prevCard=prevCard;window.answerQuiz=answerQuiz;window.nextQuiz=nextQuiz;window.rateReview=rateReview;window.timeline=timeline;window.exportData=exportData;window.importData=importData;window.resetData=resetData;
document.documentElement.style.fontSize=(S.settings.text||100)+'%';
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
S.onboarded?go(S.tab||'today'):onboarding();
