window.CHRONICLE_LESSONS.push(...[
  {
    "id":"world-mesopotamia","path":"World History","region":"Mesopotamia","year":-3500,"era":"c. 3500 BCE","minutes":7,"title":"Why the First Cities Emerged","hook":"Why would thousands of people choose to live together in dense settlements when farming villages already worked?",
    "beats":["In Mesopotamia, irrigation agriculture could produce large food surpluses, but canals required coordination, maintenance, and labor.","Surplus food supported specialists who were not full-time farmers: craft workers, merchants, priests, administrators, and soldiers.","Cities such as Uruk became centers of political authority, religion, trade, and storage. Writing developed partly from administrative needs such as tracking goods and obligations.","Urbanization brought opportunity and inequality together. Cities concentrated wealth, institutions, labor, and power."],
    "memory":"Water management creates surplus; surplus supports specialists; specialists and administration create cities.","mattered":"Cities transformed governance, economic specialization, record keeping, and social hierarchy.","connect":"Modern cities still depend on invisible systems of water, food, logistics, administration, and specialized labor.","source":"Ancient Mesopotamian archaeology and cuneiform scholarship; city formation was gradual and multi-causal.","status":"simplified",
    "quiz":[{"q":"What helped support urban growth in Mesopotamia?","o":["Irrigation and agricultural surplus","Industrial electricity","Ocean whaling","Printing presses"],"a":0,"e":"Irrigation-supported surplus could sustain dense populations and specialists."},{"q":"Why did writing develop in part?","o":["Only to write poetry","Administrative tracking of goods and obligations","To record radio broadcasts","To replace farming"],"a":1,"e":"Early writing was strongly connected to administration and accounting."},{"q":"Did cities eliminate inequality?","o":["Yes","No"],"a":1,"e":"Urbanization concentrated institutions and wealth, often increasing hierarchy."}]
  },
  {
    "id":"world-egypt-nile","path":"World History","region":"Egypt","year":-3000,"era":"Ancient Egypt","minutes":7,"title":"Egypt and the Nile as a System","hook":"Why did one river become the organizing spine of an entire civilization?",
    "beats":["The Nile concentrated water, fertile soils, transport, and settlement in a narrow corridor surrounded by desert.","Seasonal flooding historically renewed agricultural land, although the timing and scale of floods varied and required adaptation.","The river linked Upper and Lower Egypt, making movement of people, stone, grain, officials, and armies much easier than overland travel through desert.","Political authority, taxation, agriculture, religion, and transport all became intertwined with the Nile landscape."],
    "memory":"See the Nile as four systems at once: water, food, road, political spine.","mattered":"Geography did not mechanically create Egypt, but the river strongly shaped how Egyptian society could organize.","connect":"Many civilizations grew around river systems, but each transformed its environment differently.","source":"Egyptological and environmental history scholarship. Avoids the simplistic claim that geography alone determined civilization.","status":"established",
    "quiz":[{"q":"Which four roles best summarize the Nile?","o":["Water, food, transport, political connection","Coal, steel, rail, oil","Only religion","Only irrigation"],"a":0,"e":"The Nile combined ecological, economic, transport, and political functions."},{"q":"Was Nile flooding perfectly predictable every year?","o":["Yes","No"],"a":1,"e":"Flooding had patterns but varied in timing and scale."},{"q":"How did the Nile affect movement?","o":["It made transport harder","It created a major transport corridor","It prevented trade","It had no effect"],"a":1,"e":"River transport connected distant parts of Egypt efficiently."}]
  },
  {
    "id":"world-silk-roads","path":"World History","region":"Eurasia","year":700,"era":"Ancient–Medieval Eurasia","minutes":8,"title":"The Silk Roads Were Not One Road","hook":"What if the famous Silk Road was never actually a single road at all?",
    "beats":["The “Silk Roads” were overlapping land and sea routes connecting regions of Eurasia over many centuries.","Most merchants did not travel from China all the way to the Mediterranean. Goods passed through many hands, markets, and political zones.","Silk was important, but so were horses, spices, metals, glassware, paper, technologies, artistic styles, religions, and ideas.","Networks also transmitted disease. Long-distance connectivity created both opportunity and vulnerability."],
    "memory":"Do not picture a highway. Picture a relay race with goods and ideas changing hands repeatedly.","mattered":"The Silk Roads demonstrate that globalization-like networks existed long before modern container shipping.","connect":"The same network logic later appears in Atlantic trade and today’s supply chains: no single route, many nodes, cascading effects.","source":"Eurasian trade history. “Silk Road” is a modern umbrella term for many changing networks.","status":"simplified",
    "quiz":[{"q":"Were the Silk Roads a single continuous highway?","o":["Yes","No"],"a":1,"e":"They were changing networks of multiple routes."},{"q":"Did most merchants travel the entire distance from China to Europe?","o":["Yes","No"],"a":1,"e":"Goods usually moved through many intermediaries and markets."},{"q":"What moved besides goods?","o":["Ideas, religions, technologies, and disease","Nothing","Only soldiers","Only money"],"a":0,"e":"Networks transmitted culture, knowledge, and pathogens as well as commodities."}]
  },
  {
    "id":"world-black-death","path":"World History","region":"Eurasia & North Africa","year":1347,"era":"1300s","minutes":9,"title":"The Black Death","hook":"How can a disease outbreak permanently change wages, politics, religion, and the balance of power?",
    "beats":["In the mid-fourteenth century, plague spread across interconnected trade routes and devastated populations in Europe, the Middle East, and North Africa.","The bacterium Yersinia pestis is strongly associated with the pandemic. Fleas, rodents, human movement, and multiple transmission pathways contributed to spread.","Mass mortality created labor shortages in many areas. Surviving workers could sometimes demand higher wages or better terms, though rulers and elites often tried to restrict them.","The pandemic also intensified fear, religious questioning, scapegoating, and violence, including persecution of Jewish communities."],
    "memory":"Disease shock → population loss → labor scarcity → social bargaining shifts.","mattered":"The Black Death altered demographic, economic, cultural, and political trajectories across much of Eurasia and North Africa.","connect":"Pandemics are biological events and social events at the same time. Institutions determine how shocks are experienced.","source":"Historical epidemiology, archaeology, genetics, and medieval history. Transmission mechanisms remain an active research area.","status":"established",
    "quiz":[{"q":"Which bacterium is associated with the Black Death?","o":["Yersinia pestis","E. coli","Vibrio cholerae","Influenza A"],"a":0,"e":"Genetic and historical evidence strongly links Yersinia pestis to the pandemic."},{"q":"What economic effect followed severe population loss in many places?","o":["Labor became scarcer","Labor became infinite","All trade stopped forever","Wages disappeared"],"a":0,"e":"Labor shortages could strengthen workers’ bargaining positions."},{"q":"Did the pandemic have social consequences beyond mortality?","o":["No","Yes"],"a":1,"e":"It affected labor, politics, religion, social conflict, and persecution."}]
  }
]);
